version: '3'
services:
    server:
        container_name: bfl-server
        restart: always
        build: ./server
        volumes:
            - ./server:/opt/bfl
        ports:
            - 3001:3001
        command: gunicorn -b 0.0.0.0:3001 --worker-class eventlet --certfile=cert.pem --keyfile=key.pem -w 1 --reload serve:app
        depends_on:
            - alice
            - bob
        tty: true
        stdin_open: true

    bob:
        container_name: bob
        image: redis:5-alpine
        restart: always
        tty: true

    alice:
        container_name: alice
        image: postgres:11
        environment:
            - POSTGRES_DB=<BFL_DB_NAME_HERE>
            - POSTGRES_USER=<BFL_DB_USER_HERE>
            - POSTGRES_PASSWORD=<BFL_DB_PASSWORD_HERE>
        healthcheck:
            test: "pg_isready -U <BFL_DB_USER_HERE> -d <BFL_DB_NAME_HERE>"
            interval: 10s
            timeout: 5s
            retries: 5
        volumes:
            - ./db-data:/var/lib/postgresql/data

    client:
        container_name: bfl-client
        restart: always
        build: ./client
        volumes:
            - ./client/build:/opt/bfl
        ports:
            - 3000:3000
        command: "http-server -S --cors -p 3000"
