version: '3'
services:
    client:
        container_name: bfl-client
        restart: always
        build: ./client
        volumes:
            - ./client/build:/opt/bfl
        ports:
            - 3000:3000
        command: HTTPS=true HOST=bug.free.lamp serve
    
    server:
        container_name: bfl-server
        restart: always
        build: ./server
        volumes:
            - ./server:/opt/bfl
        ports:
            - 3001:3001
